# --- User Service ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 1
  selector: { matchLabels: { app: user-service } }
  template:
    metadata:
      labels: { app: user-service }
    spec:
      containers:
      - name: user-service
        image: lab-app:v17
        imagePullPolicy: IfNotPresent
        command: ["python", "src/main.py"]
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: app-secret
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-svc
  labels:
    app: user-service
spec:
  selector: { app: user-service }
  ports:
    - name: http
      port: 8000
      targetPort: 8000

# --- Stats Service ---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-service-deployment
spec:
  replicas: 1
  selector: { matchLabels: { app: stats-service } }
  template:
    metadata:
      labels: { app: stats-service }
    spec:
      containers:
      - name: stats-service
        image: lab-app:v17
        imagePullPolicy: IfNotPresent
        command: ["python", "src/main.py", "--stats"]
        ports:
        - containerPort: 8001
        envFrom:
        - configMapRef: { name: app-config }
        - secretRef: { name: app-secret }
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: stats-service-svc
  labels:
    app: user-service
spec:
  selector: { app: stats-service }
  ports:
  - name: http
    port: 8001
    targetPort: 8001
