apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage-postgres-0 # Имя формируется как <volume-name>-<statefulset-name>-<replica-index>
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi