#Секреты для паролей и токенов
apiVersion: v1
kind: Secret
metadata:
  # Имя, по которому мы будем обращаться к этому секрету
  name: app-secrets
  # Помещаем в наше рабочее пространство lab5
  namespace: lab5
type: Opaque
# stringData позволяет нам писать пароли в открытом виде,
# Kubernetes сам закодирует их при сохранении.
stringData:
  POSTGRES_PASSWORD: "Lolkek4eburek."
  POSTGRES_USER: "user"
  API_TOKEN: "your_super_secret_api_token"

#Конфигурация для адресов и настроек
apiVersion: v1
kind: ConfigMap
metadata:
  # Имя для этой карты конфигурации
  name: app-config
  namespace: lab5
data:
  # В этом URL мы используем имя пользователя и пароль, которые определили выше в Secret.
  # Наши сервисы будут использовать эту полную строку для подключения.
  DATABASE_URL: "postgresql://user:Lolkek4eburek.@postgres-svc:5432/mydatabase"
  REDIS_URL: "redis://redis-svc:6379"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-svc:5672/"
  POSTGRES_DB: "mydatabase"